const TodoListTypes = {
  SET_TODOLIST : 'SET_TODOLIST',
  SET_SUBMITDATA: 'SET_SUBMITDATA',
  ISLOADING: 'ISLOADING', 
  SET_UPDATECOMPLETE : 'SET_UPDATECOMPLETE',
  SET_DATABYID : 'SET_DATABYID',
  SET_UPDATEDATA: 'SET_UPDATEDATA',
  SET_DELETEDATA : 'SET_DELETEDATA'
}

export default TodoListTypes